# Generated by Django 4.1.2 on 2022-10-14 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GifModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('create_at', models.DateTimeField(default=datetime.datetime(2022, 10, 14, 16, 34, 29, 140104))),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gifs', models.ManyToManyField(blank=True, related_name='categories', to='gifs.gifmodel')),
            ],
        ),
    ]
