# Generated by Django 4.1.2 on 2022-10-19 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_post_released_date_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='released_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 18, 48, 48, 577550)),
        ),
    ]
